site_name: LIPID MAPS Python API
repo_url: https://github.com/s-andrews/lipidmaps_py

theme:
  name: material

nav:
  - Home: index.md
  - API: api.md
  - MODELS: models.md
  - Pathway Scoring: pathway_scoring.md
  - Custom Columns: custom_columns_guide.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true