"""Fetch and subsample a real open-data lipidomics MSI slice from METASPACE.

Produces a small, committable demo slice under ``tests/data/inputs/demo/msi/``:
an ``.imzML``/``.ibd`` cropped to a pixel bounding box, plus an ``annotations.csv``
(``name``, ``mz``, ``adduct``, ``formula``) built from the dataset's METASPACE
annotations. This overwrites the synthetic fixture generated by
``make_synth_msi_demo.py``.

Requires the optional MSI extra:  pip install lipidmaps_py[msi]
(which includes ``metaspace2020`` and ``pyimzml``).

⚠️ License: verify the source dataset permits redistribution (METASPACE datasets are
commonly CC-BY but not universally) BEFORE committing the produced slice, and record
the dataset id / DOI / license in the fixture README.

Usage:
    python scripts/fetch_msi_demo.py --dataset-id <METASPACE_DS_ID> \
        --fdr 0.1 --database "LipidMaps" \
        --bbox 40 40 90 90            # x_min y_min x_max y_max (optional crop)
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np

OUT_DIR = Path(__file__).resolve().parents[1] / "tests" / "data" / "inputs" / "demo" / "msi"


def fetch_annotations(dataset_id: str, database: str, fdr: float):
    """Return a METASPACE annotations dataframe for the dataset."""
    from metaspace import SMInstance

    sm = SMInstance()  # anonymous, read-only access to public datasets
    ds = sm.dataset(id=dataset_id)
    # results(): one row per annotation with mz, formula/ion, moleculeNames, fdr.
    results = ds.results(database=database, fdr=fdr)
    return ds, results


def annotations_to_csv(results, out_path: Path) -> int:
    """Write METASPACE annotation rows into our simple name,mz,adduct,formula CSV."""
    import csv

    written = 0
    with out_path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow(["name", "mz", "adduct", "formula"])
        for _, row in results.reset_index().iterrows():
            names = row.get("moleculeNames")
            name = names[0] if isinstance(names, (list, tuple)) and names else row.get("formula")
            mz = row.get("mz")
            if not name or mz is None or (isinstance(mz, float) and np.isnan(mz)):
                continue
            writer.writerow([name, f"{float(mz):.4f}", row.get("adduct", ""), row.get("formula", "")])
            written += 1
    return written


def subsample_imzml(src_imzml: Path, dst_imzml: Path, bbox=None) -> int:
    """Copy spectra from ``src_imzml`` into ``dst_imzml``, optionally cropping to bbox."""
    from pyimzml.ImzMLParser import ImzMLParser
    from pyimzml.ImzMLWriter import ImzMLWriter

    parser = ImzMLParser(str(src_imzml))
    kept = 0
    with ImzMLWriter(str(dst_imzml)) as writer:
        for idx, coord in enumerate(parser.coordinates):
            x, y, z = (tuple(coord) + (0, 0, 0))[:3]
            if bbox is not None:
                x0, y0, x1, y1 = bbox
                if not (x0 <= x <= x1 and y0 <= y <= y1):
                    continue
            mzs, intensities = parser.getspectrum(idx)
            writer.addSpectrum(mzs, intensities, (x, y, z))
            kept += 1
    return kept


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--dataset-id", required=True, help="METASPACE dataset id")
    ap.add_argument("--database", default="LipidMaps", help="Annotation DB (default: LipidMaps)")
    ap.add_argument("--fdr", type=float, default=0.1, help="Max FDR (default: 0.1)")
    ap.add_argument("--raw-imzml", help="Path to the dataset's original .imzML (if already downloaded)")
    ap.add_argument("--bbox", nargs=4, type=int, metavar=("X0", "Y0", "X1", "Y1"),
                    help="Inclusive pixel crop")
    args = ap.parse_args()

    OUT_DIR.mkdir(parents=True, exist_ok=True)

    ds, results = fetch_annotations(args.dataset_id, args.database, args.fdr)
    n = annotations_to_csv(results, OUT_DIR / "annotations.csv")
    print(f"Wrote {n} annotations from METASPACE dataset {args.dataset_id}")

    if args.raw_imzml:
        kept = subsample_imzml(Path(args.raw_imzml), OUT_DIR / "demo_brain.imzML",
                               bbox=tuple(args.bbox) if args.bbox else None)
        print(f"Wrote subsampled imzML slice: {kept} pixels")
    else:
        print(
            "No --raw-imzml given: annotations written, but the raw imzML/ibd must be "
            "downloaded from METASPACE (subject to the dataset's download permissions) "
            "and passed via --raw-imzml to produce the committed slice.\n"
            "Remember to record the dataset id / DOI / license in the fixture README."
        )


if __name__ == "__main__":
    main()
